version: "3"
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: monitor_db

volumes:
  postgres:
